
language: android
"jdk": "oraclejdk8",
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    
     # The BuildTools version used by your project
    # - build-tools-26.1.0
        
    # The SDK version used to compile your project
    - android-26
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
