
language: android
android:
  components:
    - tools
    
     # The BuildTools version used by your project
    - build-tools-26.1.0
    
    - platform-tools
    
    # The SDK version used to compile your project
    - android-26
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
